### ISSUE TITLE
Unable to parse integers longer than 10 digits

### ISSUE THREAD

**Issue by mchaver** [reasonml-community/bs-json#15]
I've tested this out in a couple examples and it seems throw DecodeError when it is longer than 10 digits. z2 crashes

```ocaml
type x =
  { x : int }

let decodeX json = Json.Decode.{x = field "x" int json}
let t = Js.Json.parseExn "{\"x\":1234567891}" in
let t2 =  Js.Json.parseExn "{\"x\":12345678911}" in
let z = decodeX t in
Js.log z;
let z2 = decodeX t2 in
Js.log z2;
```

**Comment by mchaver** [comment]
I just realized that int is int32 in BuckleScript.

**Comment by glennsl** [comment]
It is, but that really only applies to some integer operations, not to the value itself. In this case it's due to how it checks if the value is an integer. It's actually unintentional and can be fixed, though I'm not sure it should be. But let me reopen and think about it for a bit...

**Comment by mchaver** [comment]
`float` seems to be able to handle a lot longer values. Maybe it should check if it is a int64?

**Comment by glennsl** [comment]
They're all just JavaScript numbers at run time, it's just a matter of how they're interpreted. I've fixed the rejection in `Json.Decode.int`, but in the process discovered that OCaml will overflow int literals > `Int32.max_int` without warning, which is a bit scary. But it's at least a known issue that will eventually be fixed: https://github.com/BuckleScript/bucklescript/issues/373
