### ISSUE TITLE
This open statement shadows the value identifier float

### ISSUE THREAD

**Issue by thomasthiebaud** [reasonml-community/bs-json#16]
Hej, I'm trying to create a simple working example based on the examples. It is working but I get a warning. Here my code

```
type random = {
    number: float
};

module Decode = {
    let random = (json) =>
        Json.Decode.{
            number: json |> field("number", float)
        };
};

let fetchRandomNumber = (callback) =>
    Js.Promise.(
        Fetch.fetch(apiBaseUrl)
        |> then_(Fetch.Response.json)
        |> then_((payload) => {
            callback(Decode.random(payload));
            resolve(None)
        })
    );
```

I get this warning everytime

```
module Decode = {
  let random = (json) =>
    Json.Decode.{
      number: json |> field("number", float)
    };
};
this open statement shadows the value identifier float (which is later used)
```

Can it be related to the `bs-json` library ?

**Comment by glennsl** [comment]
I assume you're the @Tom that asked this on Discord too, but just in case someone else comes looking:

`float` shadows the automatically imported `Pervasives.float`. The compiler emits this warning in case you actually wanted `Pervasives.float`. The solution is to reassure the compiler by being explicit about which function you want by fully qualifying it, in this case by using `Json.Decode.float`.
