### ISSUE TITLE
parseOrRaise not in latest published version (docs out of sync)

### ISSUE THREAD

**Issue by aaronshaf** [reasonml-community/bs-json#18]

**Comment by glennsl** [comment]
It is now. It sometimes takes more than a second between making a commit and publishing it :)

If you want the documentation to accurately reflect the published version, you need to go to where it's published (NPM, or after some delay on redex). Alternatively you can look at the release tag in the repository. The documentation in the master branch of the repository will usually reflect the unreleased in-development API, and is not intended to be in sync with anything published.
