### ISSUE TITLE
Docs: decoding nested field

### ISSUE THREAD

**Issue by aaronshaf** [reasonml-community/bs-json#19]

**Comment by glennsl** [comment]
This is documented here, with examples: https://github.com/reasonml-community/bs-json/blob/master/src/Json_decode.mli#L309-L324

It woud have been nice to have better API documentation in general, but this is unfortunately not very practical at the moment. Hopefully there'll be a good doumentation generator soon.

Closing as resolved. Please reopen if you had a more specific problem in mind.
