### ISSUE TITLE
Safe Decode?

### ISSUE THREAD

**Issue by raqystyle** [reasonml-community/bs-json#20]
First of all, thank you for the great decoding lib!

I'm new to Reason. I'm struggling with catching the exceptions that occur while decoding JSON. I have a simple decoder

```reason
let decodeState = (json: Js.Json.t): state =>
  Json.Decode.{
    ctr: json |> field("ctr", int)
  };
```

and I use like this:

```reason
let restore = (): state => {
  switch Dom.Storage.(localStorage |> getItem("test-data")) {
    | None => init
    | Some(stateStr) => {
      try (decodeState(Json.parseOrRaise(stateStr))) {
        | Json.ParseError(e) => {
          Js.log2("2. Error:", e);
          init
        }
      };
    }
  };
};
```

I altered the entry in my `localStorage` so that I don't have a string there instead of a number. The program crashes with `Json_decode.DecodeError,5,Expected number, got "not_a_number"` and I can't catch the exception.

How to I help it?

**Comment by glennsl** [comment]
Hi. What do you mean you can't catch the exception? Have you tried adding a branch for `DecodeError` to the try block?

```ml
      try (decodeState(Json.parseOrRaise(stateStr))) {
        | Json.ParseError(e) => ...
        | Json.Decode.DecodeError(e) => ...
      };
```

should work fine.

**Comment by raqystyle** [comment]
@glennsl `Json.Decode.DecodeError` is what I was missing. Thank you! But I didn't know I had to add this branch as well. The compiler didn't argue back that my check is not exhaustive enough. I'm I missing something?

**Comment by raqystyle** [comment]
@glennsl Actually, I was mislead (maybe, this word is too strong) by the documentation for the `Json.parseOrRaise` which states: `parse s returns a Js.Json.t if s is a valid json string, raises ParseError otherwise`. Anyway, thank you for the help!

**Comment by glennsl** [comment]
There's unfortunately no exhaustiveness checking for exceptions. Parsing and decoding are different processes, and you need to check for errors from both. It can be a valid json string and still not fit the shape you need, in which case it will raise a DecodeError.

There are libraries that do provide exhaustiveness checking of errors, like [JsonR](https://redex.github.io/packages/json-r) and [JsonCodec](https://redex.github.io/packages/unpublished/state-machine-systems/JsonCodec), but it comes at a cost.

**Comment by raqystyle** [comment]
@glennsl Oh, I see. Thank you for explanation!
