### ISSUE TITLE
Can't find list.js

### ISSUE THREAD

**Issue by niklasnisbeth** [reasonml-community/bs-json#3]
I install bs-json with npm --save and added it as a dependency to bsconfig.json.

Attempting to use it, I get the following error message in browser console:

`Error: Cannot find module 'bs-platform/lib/js/list.js' from 'bs-json/lib/js/src/json_decode.js'`

The file is there remotely, but shouldn't it be compiled into the code somehow? I must be missing a configuration step?

I am using brunch, and I can successfully use the bs-fetch module that's also in this organization.

**Comment by glennsl** [comment]
Hmm, this seems like it might be a brunch-specific issue, and I know next to nothing about brunch. What do you mean it's there remotely, and that it should be compiled into code somehow?

It might be because bs-platform is a devDependency, so if you don't have bs-platform installed in your own project it would cause issues, but then your project wouldn't really work anyway.

**Comment by niklasnisbeth** [comment]
I mean that I do have the file bs-platform/lib/js/list.js in node_modules on the server, it's seemingly just not being included in the code that gets compiled into app.js and sent to the client. 

The bs-json code gets copied into my app.js verbatim, the `require`s are still there with the paths to files in bs-platform that the client doesn't have access to. Is that how it's supposed to look, or is there a problem with my bucklescript/brunch setup?

This is my `bsconfig.json`:

```
{
  "name": "test",
  "sources": "bucklescript",
  "bs-dependencies": ["bs-fetch", "bs-json"],
  "bsc-flags": [ "-no-alias-deps"]
}
```

**Comment by glennsl** [comment]
Yes, this seems like a configuration issue with your bundler. Again, I know nothing about brunch, but it seems odd that it would bundle `bs-json` without bundling its dependencies.

Your `bsconfig.json` looks fine. With this config, bucklescript will compile each OCaml/Reason file into a commonjs module. BuckleScript itself doesn't do any bundling, so it must be your burnch config.

**Comment by niklasnisbeth** [comment]
OK, thanks very much for the help.

**Comment by GoNZooo** [comment]
@niklasnisbeth Did you ever manage to solve this? I'm running into the what seem like the same issues with brunch and bucklescript.
