### ISSUE TITLE
Number.isInteger() throws error in IE

### ISSUE THREAD

**Issue by logason** [reasonml-community/bs-json#5]
`Number.isInteger()` (https://github.com/reasonml-community/bs-json/blob/master/src/Json_decode.ml#L1) is not supported in IE (https://caniuse.com/#search=isInteger). Don't know what is the best way to solve this. One would be providing polyfill, that's not very elegant but was the workaround we did in our project to bypass this error:

```
[%bs.raw
  {|Number.isInteger = Number.isInteger || function(value) {
  return typeof value === 'number' && isFinite(value) && Math.floor(value) === value;
}|}];
```

**Comment by glennsl** [comment]
Bummer :( Can't say I'm surprised that IE craps out even at something as basic as this, but seems an easy fix. Just a sec...

**Comment by glennsl** [comment]
Fixed. Thanks for reporting! :)

**Comment by logason** [comment]
I was kind of impressed that it even managed to fail at this 😄

Thanks for super fast response! 🎉 💥
