### ISSUE TITLE
File names don't resolve on OS X

### ISSUE THREAD

**Issue by Lokeh** [reasonml-community/bs-json#6]
After installing the library, I was getting this error when trying to use it:

```Module not found: `/Users/will/Code/reason/autocomplete/node_modules/bs-json/lib/js/src/json_decode.js` does not match the corresponding path on disk `Json_decode.js`.```

It looks like a recent update to BuckleScript changed the way that the compiled js files are named, switching to beginning with lowercase. The `require` statements generated also expect the file names to begin with lowercase.

Running `bsb -clean-world` fixed the issue, but the checked-in `js/` folder should probably be corrected to avoid issues with people installing for the first time.

**Comment by glennsl** [comment]
Hi! Sorry I've missed this somehow. It looks to me like the checked in js-files are correct. Is there a specific instance I've missed?

**Comment by Lokeh** [comment]
I think it seems to be a problem with `bs-loader` used in `react-scripts`. The checked in files are in title case, `Json_decode.js`, but `bs-loader` is emitting require's that reference `json_decode.js`.

I can't tell if it's a problem with `bs-loader`, or `bucklescript` - it's very strange. It definitely seems to be related to https://github.com/reasonml-community/bs-loader/issues/19

**Comment by glennsl** [comment]
Closing this for probably being a problem with bs-loader, which is deprecated anyway. But reopen if needed.
