### ISSUE TITLE
DecodeError vs Js_result.t

### ISSUE THREAD

**Issue by mchaver** [reasonml-community/bs-json#8]
`Js_result` from the BuckleScript library provides `Ok` and `Error`. This forces you to catch and handle errors at the type level whereas `DecodeError` is a runtime error. You can choose to ignore but it will still appear in the runtime. Any reason to prefer a runtime error over a type level one?

**Comment by mchaver** [comment]
I've recoded it with `Js_result`, missing the examples and tests though.
https://github.com/plow-technologies/bs-json/blob/type-safe/src/Json_decode.ml

I think the biggest drawback is it makes `field` very verbose, this would get really ugly with a big record:

```OCaml
type point = {
  x: float;
  y: float
}

let decodePoint json =
  match field "x" float json with
  | Js_result.Ok x ->
    (match field "y" float with
    | Js_result.Ok y -> Js_result.Ok { x = x ; y = y}
    | Js_result.Error err -> Js_result.Error err
    )
  | Js_result.Error err -> Js_result.Error err
```

whereas with errors you can do something like:

```OCaml
let decodePoint json =
  match 
  { x = field "x" float json
  ; y = field "y" float json
  } with
  | v -> Some v
  | exception Json.Decode.DecodeError _ -> None
```

Trying to figure out if it is possible to chain fields with `Js_result`.

**Comment by glennsl** [comment]
Yes, that's pretty much the reason. We could define `mapX` functions to make it a little bit less verbose, but the lack of first-class type constructors in OCaml doesn't help either.

Eventually we'll get generated json encoders and decoders which can use `result`, but until then I find the current trade-off to be better. There are a few other libraries that use `result` however, if you really want that: [JsonR](https://github.com/cxa/JsonR) and [JsonCodec](https://github.com/state-machine-systems/JsonCodec)

**Comment by glennsl** [comment]
I'll close this for now, but feel free to continue the discussion if you come across something interesting.
